### PR TITLE
fix(index): Change header field name to `Authorization`

### LINKED ISSUE #38: Fix `NetworkManager` initial header
In `index.tsx`
```
const networkManager = new NetworkManager({
  headers: {
    common: {
      Authentication: authenticationManager.getToken()
    }
  }
});
``` 
should be 
```
const networkManager = new NetworkManager({
  headers: {
    common: {
      Authorization: generateAuthorizationHeaderValue(authenticationManager.getToken())
    }
  }
});
```

### PR DESCRIPTION
**Pull request by bilgeyucel**
Closes #38

### CODE REVIEW

**Review by mucahit — APPROVED** [review]

File: src/index.tsx [hunk 1]
```diff
@@ -19,12 +19,13 @@ import authenticationManager from "./authentication/util/authenticationManager";
...
 import {ReduxStoreShape} from "./core/redux/models/store";
 import authenticationApi from "./authentication/api/authenticationApi";
+import {generateAuthorizationHeaderValue} from "./core/network-manager/networkUtils";
 
 // initSentry();
 const networkManager = new NetworkManager({
   headers: {
     common: {
-      Authentication: authenticationManager.getToken()
+      Authorization: generateAuthorizationHeaderValue(authenticationManager.getToken())
```
Comment (burakguneli) [inline src/index.tsx:28]: I'm not sure about this. Since the BE team changes the authentication type to session auth, probably we won't need this header any more in the new projects

**Review by burakguneli — CHANGES_REQUESTED** [review]

File: src/index.tsx (hunk 1 above)
Comment (bilgeyucel) [reply src/index.tsx:28]: You may be right. However, currently, it is a bug. 
Also, as far as I know, the backend team still uses their starter package with token authentication. I think it's important to be in sync with them.

**Review by edizcelik — APPROVED** [review]

File: src/index.tsx (hunk 1 above)
Comment (edizcelik) [reply src/index.tsx:28]: Yes we can keep the token authentication for now and add a guideline for switching to cookie authentication
